version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginxreverseproxy
    container_name: nginx-reverse-proxy
    tty: true
    networks:
      - node-network
    depends_on:
      - node
    ports:
      - 8080:80

  node:
    build:
      context: .
    container_name: node
    networks:
      - node-network
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    tty: true
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge